### ISSUE TITLE
`--zip` for `push`

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#83]
Let's make it possible for the `push` command to zip the entire package and provide `Content-Type: application/zip` HTTP header. By default, this option should be ON, while it should be possible to use `--no-zip` to disable it.

**Comment by tank-bohr** [comment]
@yegor256 may I take this one?

I have a proposal to use [`Content-Encoding: gzip`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) instead of `Content-Type: application/zip` to let an HTTP client do all the dirty work (as Typhoeus is used, it will be done by libcurl). And on to the receiver party, it will be much easier as we can use [Rack::Deflater](https://github.com/rack/rack/blob/99c4598605b89bbde2efe32de94e6bedf989bb4a/lib/rack/deflater.rb#L3). It also will be backward-compatible.

**Comment by yegor256** [comment]
@tank-bohr I agree, go for it

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.0`
